### ISSUE TITLE
No longer working.

### ISSUE THREAD

**Issue by LocalsGitHub** [Wizz1337/TikTokMassViewbotting#2]
No views are added.

**Comment by sam1e-dev** [comment]
It is working, you just have to wait, i got like 78k views in 10 hours, its not much but if you can implement proxies i think it would work again

**Comment by LocalsGitHub** [comment]
It's been 12 hours and 0 views have been added

**Comment by Wizz1337** [comment]
Im trying to bypass the ratelimit.Check if i make new updates
